management:
  endpoints:
    web:
      exposure:
        include: "*"


battery:
  e-auth-token: dddd
  morning-reserve: 10
  day-reserve: 30
  night-reserve: 45
  morning-enabled: true
  day-enabled: true
  night-enabled: true
  morning-cron: "0 00 5 * * MON-FRI"
  day-cron: "0 0 9 * * MON-FRI"
  night-cron: "0 30 20 * * SUN-FRI"
server:
  error:
    whitelabel:
      enabled: false